### ISSUE TITLE
Command to delete files

### ISSUE THREAD

**Issue by thebatclaudio** [thebatclaudio/batman-listening-things#7]
Create a command to delete files after 1 day

**Comment by MagnaibayarMN** [comment]
Hello, I wanna be assigned. Could please describe more. 
For an example: which files of directory we have to delete?

**Comment by thebatclaudio** [comment]
Hello!
You should delete files on `storage/app/public/generated`
You can find generated videos on `generated_videos` table (with timestamps, so you can take only the videos that were generated more than 24 hours ago)

Let me know!

**Comment by thebatclaudio** [comment]
Hey @MagnaibayarMN,
how is it going? Have you already started working on this issue?

I'm asking because my VPS is exploding with so many files and I'm forced to delete them manually 😅

**Comment by MagnaibayarMN** [comment]
I apologize for that 🙏🏻, please review this [PR](https://github.com/thebatclaudio/batman-listening-things/pull/13)

**Comment by thebatclaudio** [comment]
It works great! Thank you @MagnaibayarMN!
